"""empty message

Revision ID: 43463d81bcb0
Revises: 34db5893dd35
Create Date: 2024-03-27 22:17:49.303683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43463d81bcb0'
down_revision = '34db5893dd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_members', schema=None) as batch_op:
        batch_op.drop_constraint('task_members_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('task_members_task_id_fkey', type_='foreignkey')
        batch_op.drop_column('task_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('task_members_task_id_fkey', 'task', ['task_id'], ['id'])
        batch_op.create_foreign_key('task_members_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
